---
wordpress_db_name: wordpress
wordpress_db_user: wordpress
wordpress_db_host: "{{ mysql_host | default('localhost')}}"
wordpress_home: "{{ websites_home }}/{{ wordpress_domain }}"
wordpress_version: "4.1"
wordpress_sha256: "3743d82698571903382dc223940e712f7bb5cfd20cedba7b7c32c97d470defab"
wordpress_url: "{{ wordpress_domain }}"
wordpress_email: "{{webmaster}}@{{wordpress_domain}}"
