---
  - name: install OS updates
    apt: update_cache=yes upgrade=full

  - name: install essential vince packages
    apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
    with_items:
      - ack-grep
      - build-essential
      - curl
      - git
      - less
      - ntp
      - ntpdate
      - python-software-properties # provides the add-apt-repository cmd
      - screen
      - sqlite3
      - tree
      - vim-nox
      - wget

  - name: start the ntp service
    service: name=ntp state=started enabled=true
