---
- name: Database server for testing only
  hosts: database-servers
  sudo: yes

# WARNING: Explicitly not bothering to secure the mysql root user. This
# configuration is for testing only. If this were a production config you would
# need to change the root password and store a .my.cnf file.
# For some good ideas on production configs:
# https://github.com/geerlingguy/ansible-role-mysql

  tasks:
    - name: install MariaDB database server
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
          - mariadb-server
          - mariadb-client
          - python-mysqldb # required for ansible mysql modules to work

    - name: Remove anonymous MySQL user
      mysql_user: name='' state=absent

    - name: Remove MySQL test database
      mysql_db: name=test state=absent

    - name: start mysql service
      service: name=mysql state=started enabled=yes
