---
- hosts: database-servers
  sudo: yes
# WARNING: Explicitly not bothering to secure the mysql root user. This
# configuration is for testing only. For some good ideas on production configs:
# https://github.com/geerlingguy/ansible-role-mysql
  tasks:
    - name: install MariaDB database server
#      notify: restart apache
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
          - mariadb-server
          - mariadb-client
          - python-mysqldb # required for ansible mysql modules to work

    - name: Remove anonymous MySQL user
      mysql_user: name='' state=absent

    - name: Remove MySQL test database
      mysql_db: name=test state=absent

    - name: create the wordpress database
      mysql_db: name=wordpress state=present

    - name: Ensure Wordpress user
      mysql_user: name={{ wordpress_db_user | default('wordpress') }}
                  priv=wordpress.*:ALL
                  password={{ wordpress_db_pass }}
