---
- name: Efficient Apache/PHP setup
  # This playbook does the base setup for an Apache/PHP server. It
  # uses system packages from Ubuntu/Debian, setting up Apache as the
  # main server, with php5-fpm managing PHP in separate processes.
  # Apache communicates with PHP via mod_proxy_fcgi, keeping the
  # Apache processes lightweight and efficient.
  hosts: wordpress-servers
  sudo: yes
  vars:
    defaultsite_root: /home/webmaster/websites/default
  tasks:
    ##################################################################
    # Apache 2.4 setup
    ##################################################################
    - name: install apache web server
      notify: restart apache
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
          - apache2
          - python-passlib # required for ansible htpasswd module

    - name: activate common apache2 modules
      notify: restart apache
      apache2_module: name={{ item }} state=present
      with_items:
          #- access_compat # as Ubuntu configures it, this is ineffective.
          - alias
          - auth_basic
          - auth_digest
          - auth_form
          - authn_core
          - authn_file
          - authz_core
          - authz_host
          - authz_user
          - deflate
          - dir
          - env
          - expires
          - filter
          - include
          - info
          - mime
          - negotiation
          - proxy
          - proxy_fcgi
          - rewrite
          - setenvif
          - status

    - name: create a webmaster group
      group: name=webmaster state=present

    - name: create a webmaster user
      user: name=webmaster
            group=webmaster
            state=present
            update_password=on_create
            password={{ webmaster_crypt_pass }}
            home=/home/webmaster

    - name: create the website directories
      # Should auto-create all parent dirs with same permissions.
      file: path={{ defaultsite_root }}/public_html/adm
            state=directory
            owner=webmaster
            group=webmaster
            mode=0755

    - name: install htpasswd file for default host
      # Store outside the docroot! Set up to be readable only by web server
      htpasswd: path={{ defaultsite_root }}/htpasswd
                state=present
                name=webmaster
                password={{ webmaster_pass }}
                owner=webmaster
                group=www-data
                mode=0640

    - name: install a default index page
      copy: src=files/index.html
            dest={{ defaultsite_root }}/public_html/index.html
            owner=webmaster
            mode=0644

    - name: install a default apache vhost
      notify: restart apache
      template: src=templates/apache2_vhost.j2 dest=/etc/apache2/sites-available/001-default.conf

    - name: disable the system default apache vhost
      notify: restart apache
      command: a2dissite 000-default
               removes=/etc/apache2/sites-enabled/000-default.conf

    - name: enable our installed default apache vhost
      notify: restart apache
      command: a2ensite 001-default
               creates=/etc/apache2/sites-enabled/001-default.conf

    - name: start apache2 daemon
      service: name=apache2 state=started enabled=true

    ##################################################################
    # PHP 5 FPM setup
    ##################################################################

    - name: install PHP and related libraries
      notify: restart php5-fpm
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
          # See list of Wordpress reqs
          # http://wordpress.stackexchange.com/questions/42098/
          - php5-fpm
          - php5-cli
          - php5-curl
          - php5-gd
          - php5-imagick
          - php5-json
          - php5-mysql

    - name: set php-fpm to listen on TCP instead of UDS
      notify: restart php5-fpm
      ini_file: dest=/etc/php5/fpm/pool.d/www.conf
                backup=yes
                section=www
                option=listen
                value={{ fastcgi_listen }}

    - name: restrict php-fpm to respond to local connections only
      notify: restart php5-fpm
      ini_file: dest=/etc/php5/fpm/pool.d/www.conf
                backup=yes
                section=www
                option=listen.allowed_clients
                value=127.0.0.1

    - name: add a PHP test page
      copy: src=files/phptest.php
            dest={{ defaultsite_root }}/public_html/adm/phptest.php
            owner=webmaster
            mode=0644

    - name: start the php5-fpm service
      service: name=php5-fpm state=started enabled=true


  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

    - name: restart php5-fpm
      service: name=php5-fpm state=restarted
