---
##################################################################
# PHP 5 FPM setup
##################################################################

- name: install PHP and related libraries
  notify: restart php5-fpm
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
      # See list of Wordpress reqs
      # http://wordpress.stackexchange.com/questions/42098/
      - php5-fpm
      - php5-cli
      - php5-curl
      - php5-gd
      - php5-imagick
      - php5-json
      - php5-mysql

- name: set php-fpm to listen on TCP instead of UDS
  notify: restart php5-fpm
  ini_file: dest=/etc/php5/fpm/pool.d/www.conf
            backup=yes
            section=www
            option=listen
            value={{ fastcgi_listen }}

- name: restrict php-fpm to respond to local connections only
  notify: restart php5-fpm
  ini_file: dest=/etc/php5/fpm/pool.d/www.conf
            backup=yes
            section=www
            option=listen.allowed_clients
            value=127.0.0.1

- name: add a PHP test page
  copy: src=phptest.php
        dest={{ defaultsite_root }}/public_html/adm/phptest.php
        owner=webmaster
        mode=0644

- name: start the php5-fpm service
  service: name=php5-fpm state=started enabled=true
