---
webmaster: webmaster
webmaster_group: "{{webmaster}}"
webmaster_home: /home/{{webmaster}}
websites_home: "{{webmaster_home}}/websites"
defaultsite_root: "{{websites_home}}/default"
defaultsite_domain: localhost
http_service: apache2
http_service_user: www-data
http_service_group: www-data
apache_modules:
  #- access_compat # as Ubuntu configures it, this is ineffective.
  - alias
  - auth_basic
  - auth_digest
  - auth_form
  - authn_core
  - authn_file
  - authz_core
  - authz_host
  - authz_user
  - deflate
  - dir
  - env
  - expires
  - filter
  - include
  - info
  - mime
  - negotiation
  - proxy
  - proxy_fcgi
  - rewrite
  - setenvif
  - status
